# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: http://mofengfly.githup.io
url: http://mofengfly.githup.io
date_format: "ordinal"
title: 在路上
author: 在路上 
paginate: 9

# ---------------- #
#   RSS / Email    #
# ---------------- #
subscribe_rss: /atom.xml
email:

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough"]
pygments: true
permalink: /:year/:month/:day/:title
gems:
    - jekyll-sitemap

# ---------------- #
#      Comments    #
# ---------------- #
duoshuo_short_name: 在路上

# ---------------- #
#      Adsense     #
# ---------------- #
adsense: false
amazon: true
