auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: mofengfly.githup.com
url: http://mofengfly.githup.com
feed: /atom.xml
author_info: <a href="http://mofengfly.githup.com/">在路上</a>
